### ISSUE TITLE
Use black for formatting python code

### ISSUE THREAD

**Issue by cacoze** [yamawakimiho/memo#2]
Hi @yamawakimiho , it's a good practice to have your python code formatted in such a way that's easy to read. There are a lot of tools that can helps us with that, and [black](https://pypi.org/project/black/) is one of the most used here at Labcodes and one that I recommend. (btw, it has a integration with VS code that might be helpful for you)

I noticed some pieces of code in this repo that could be improved using the style proposed by black.

**Comment by yamawakimiho** [comment]
This issue has been solved and merged with issue #1 .
